### ISSUE TITLE
About the community fork

### ISSUE THREAD

**Issue by mrnossiom** [tower-lsp/tower-lsp#1]
For initial discussion, see https://github.com/ebkalderon/tower-lsp/issues/427

I see that most of the people are interested in a maintained fork, but it seems that no one wants to be the one creating the org nor has taken the first steps. With this in mind, I've created the org [`tower-lsp`](https://github.com/tower-lsp) to kickstart the effort, and a few of you have already been invited to join. 

A few points that should be addressed:

- How should we proceed on the fork: https://github.com/tower-lsp/tower-lsp/issues/2

- Under what name is this fork going to live: https://github.com/tower-lsp/tower-lsp/issues/3

- How should the community leadership organize itself.

  I've created the org to kickstart the fork, but I understand that may raise some concerns. Yet, as `tower-lsp` was mainly built by Eyal alone, no one has legitimacy to lead the community fork. I have no issue with ceasing leadership to someone else if some discussion decides so.

I have not yet added any commit because I want to fully discuss the process beforehand. 

Please tell me how you feel about this fork, and how you would resolve the questions above.

**Comment by uncenter** [comment]
Thoughts on splitting each of those priorities into a separate issue to organize discussion more clearly?

**Comment by trevor-scheer** [comment]
Thanks for starting this! I’ll be more involved when I’m able, closer to the end of the month.
