### ISSUE TITLE
Kickoff the fork from a codebase point of view

### ISSUE THREAD

**Issue by mrnossiom** [tower-lsp/tower-lsp#2]
What are the next actions to take in the codebase and in what order

Right now, what I have in mind is:

- [x] upgrade `tower` to v0.5 and `lsp-types` to v0.97 #6 
- [x] upgrade the CI #8
- [ ] add support for new LSP features (e.g. notebook support)
  See https://github.com/ebkalderon/tower-lsp/pulls?q=is%3Apr+is%3Aopen
- [ ] address issues from the original repository and merge PRs

**Comment by idealseal** [comment]
What should also be done is updating the CI actions to their latest version and remove or replace the unmaintained `action-rs` actions.
